### PR TITLE
feat: handle og deleted proposals

### PR DESCRIPTION
**Pull request by md0x**
Changes proposed in this PR:
- Handle OG deleted proposals

### CODE REVIEW

**Review by mrice32 — APPROVED** [review]

**Review by mrice32 — APPROVED** [review]
LGTM!

**Comment by ryanwolhuter** [comment]
There's something here that I don't quite understand.

We are using the assertion ID as the id of the proposal, but we know that the assertion ID can be different if a proposal is disputed. In this case, the actual assertion ID associated with a proposal will be zero or else it will be the assertion ID of a new assertion.

This leads to an issue: 

We're using a field that can change as a unique id, so we can't actually look up proposals by their id fields.

For example with the above, we're adding a `deleted` property to a proposal with a given id. but in that case, the contract then deletes that mapping. so then if someone else proposes again, that proposal will have a different id, and we will lose the information that the proposal was deleted. else we would continue to use the old assertion id as the id of the proposal, and the state of the graph and the contract will get out of sync.

It seems to me that the only uniquely identifying piece of information that we have for a given proposal is the proposal hash. This will always be unique (at least according to my logic) because it contains the ipfs url, which itself contains a hash of the content etc. 

So to me, the only thing that actually will work here is to rather use the proposal hash as the id of a proposal. then we could look up proposals by their proposal hashes, an o(1) lookup. This will also prevent the issue where a proposal is keyed by an assertion id that no longer exists. 

At the moment the only way to correctly find a given proposal is to query them all and then look for the one with the matching proposal hash.

@mrice32 @daywiss @md0x @Reinis-FRP what do you think?

**Comment by Reinis-FRP** [comment]
> It seems to me that the only uniquely identifying piece of information that we have for a given proposal is the proposal hash. This will always be unique (at least according to my logic) because it contains the ipfs url, which itself contains a hash of the content etc.

No, the proposal hash does not include ipfs url. It is solely based on proposed transactions. If there are multiple Snapshot proposals with the same transaction (e.g. funding same amount in tranches), they will all share the same proposal hash. Thus, for unique identification you would need to add explanation field.

**Comment by ryanwolhuter** [comment]
My bad, I meant a combination of the explanation and hash. 

Actually could we not just use only the explanation @Reinis-FRP

**Comment by Reinis-FRP** [comment]
> Actually could we not just use only the explanation @Reinis-FRP

Yes, this would work for oSnap. Just note that other integrations using OptimisticGovernor contract (we don't have them) could have other interpretation of the explanation field than IPFS hash of off-chain proposal.

**Pull request merged**
